# docker build -t twizy_humble -f docker/simulation/Dockerfile.humble .

FROM osrf/ros:humble-desktop-full

RUN apt update && apt install -y \
    git \
    nano \
    wget \
    python3-pip \
    python3-rosdep && \
    ros-humble-gazebo-ros \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

# ADD . /root/ros2_ws/src 

# RUN ~/ros2_ws/src && colcon build

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

